{% set name = "apache-airflow-providers-apache-spark" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-spark-{{ version }}.tar.gz
  sha256: a6ebc5a24958a727d2c2c3f0a8db0be634cfedfd327c319baacf6a58653873c6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - pyspark

test:
  imports:
    - airflow.providers.apache.spark
    - airflow.providers.apache.spark.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Spark for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-spark/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
