{% set name = "apache-airflow-providers-apache-spark" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-spark-{{ version }}.tar.gz
  sha256: f097703b677c87934cd633ef9a133f7ff6f11c857a947bfe5d1ec0caf523ea1b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - apache-airflow >=2.1.0
    - pyspark
    - python >=3.6

test:
  imports:
    - airflow.providers.apache.spark
    - airflow.providers.apache.spark.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Spark for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-spark/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
